Models/ErrorViewModel.cs
using System;

namespace FoodTruckFinder.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FoodItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FoodTruckFinder.Models
{
    public class FoodItem
    {
        [Key]
        public string Name { get; private set;}
        public FoodItem(string name)
        {
            Name = name;
        }
    }
}

Models/FoodTruck.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FoodTruckFinder.Models
{
    public class FoodTruck
    {
        public FoodTruck()
        {

        }
        public FoodTruck(long id, string desc)        {
            LocationId = 1;
            LocationDesc = desc;
        }
        public FoodTruck(long LocationId, string facilityType, string locationDesc, string address, string status, List<FoodItem> items, Location loc)
        {
            this.LocationId = LocationId;
            this.FacilityType = facilityType;
            this.LocationDesc = locationDesc;
            this.Address = address;
            this.Status = status;
            this.FoodItems = items;
            this.Location = loc;
        }
                      
        [Key]
        public long LocationId { get; set; }

        public string LocationDesc { get; set; }
        public string FacilityType { get; set; }
        public string Address { get; set; }

        public string Status { get; set; }

        public List<FoodItem> FoodItems { get; set; }
        public Location Location {get;set;}
    }
}

Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FoodTruckFinder.Models
{
    public class Location
    {
        [Key]
        public decimal Longtitude { get; private set; }
        public decimal Latitude { get; private set; }
        public Location(decimal latitude, decimal longtitude)
        {
            this.Latitude = latitude;
            this.Longtitude = longtitude;
        }
    }
}

Controllers/FoodTruckController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodTruckFinder.Data;
using FoodTruckFinder.Models;

namespace FoodTruckFinder.Controllers
{
    public class FoodTruckController : Controller
    {
        private readonly FoodTruckContext _context;

        public FoodTruckController(FoodTruckContext context)
        {
            _context = context;
        }

        // GET: all food trucks
        public async Task<IActionResult> Index()
        {
            return View(await _context.FoodTruck.ToListAsync());
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FoodTruckFinder.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FoodTruckFinder.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/FoodTruck/Index.cshtml
@model IEnumerable<FoodTruckFinder.Models.FoodTruck>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LocationDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FoodItems)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LocationDesc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FoodItems)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Food Truck Finder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="FoodTruck" asp-action="Index">Food Truck Finder</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Food Truck Finder - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>